# k8s/prod/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 声明你要生成的 Secret
secretGenerator:
  - name: wechat-secret
    envs:
      - .env # 动态读取本地的 .env 文件

# 引用其他的资源文件
resources:
  - app-deployment.yaml
  - nginx-deployment.yaml
  - redis-deployment.yaml
  - ingress.yaml
